name: Run Robot Tests via TestRail

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Comma-separated list of tags'
        required: true
        default: 'smoke'

jobs:
  run-robot:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v4
      # - uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.12.11'
      # - run: pip install -r requirements.txt
      # - name: Run Robot
      #   run: |
      #     mkdir -p results
      #     echo "Running with tags: ${{ github.event.inputs.tags }}"
      #     robot --outputdir results -i "${{ github.event.inputs.tags }}" tests/
      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: robot-results
      #     path: results/
      - run: echo "Hello World"
